// Meridian RCM - Demo Data
// All realistic healthcare RCM data embedded for Vercel deployment

export const CLAIMS = [
  { id:'1', claim_number:'CLM-2024-00001', patient_name:'Robert Johnson', practice_name:'Austin Family Medicine', payer_name:'Blue Cross Blue Shield TX', service_date:'2024-12-01', total_charge:250, total_paid:160, patient_resp:40, status:'paid', primary_icd:'J06.9', cpt_codes:'99213', days_in_ar:0, provider:'Dr. Emily Chen', filing_date:'2024-12-02' },
  { id:'2', claim_number:'CLM-2024-00002', patient_name:'Patricia Williams', practice_name:'Austin Family Medicine', payer_name:'Aetna', service_date:'2024-12-03', total_charge:350, total_paid:238, patient_resp:42, status:'paid', primary_icd:'M54.5', cpt_codes:'99214', days_in_ar:0, provider:'Dr. Emily Chen', filing_date:'2024-12-04' },
  { id:'3', claim_number:'CLM-2024-00003', patient_name:'Michael Brown', practice_name:'Austin Family Medicine', payer_name:'UnitedHealthcare', service_date:'2025-01-15', total_charge:450, total_paid:null, patient_resp:null, status:'submitted', primary_icd:'E11.65', cpt_codes:'99215, 83036', days_in_ar:47, provider:'Dr. Emily Chen', filing_date:'2025-01-16' },
  { id:'4', claim_number:'CLM-2024-00004', patient_name:'Jennifer Davis', practice_name:'Lone Star Orthopedics', payer_name:'Cigna', service_date:'2025-01-20', total_charge:1200, total_paid:null, patient_resp:null, status:'pending_payer', primary_icd:'M17.11', cpt_codes:'27447', days_in_ar:42, provider:'Dr. Mark Rivera', filing_date:'2025-01-21' },
  { id:'5', claim_number:'CLM-2024-00005', patient_name:'David Martinez', practice_name:'Lone Star Orthopedics', payer_name:'Medicare', service_date:'2024-11-10', total_charge:850, total_paid:0, patient_resp:0, status:'denied', primary_icd:'M23.611', cpt_codes:'29881', days_in_ar:113, provider:'Dr. Mark Rivera', filing_date:'2024-11-11', denial_code:'CO-197', denial_reason:'Prior authorization not obtained' },
  { id:'6', claim_number:'CLM-2024-00006', patient_name:'Linda Anderson', practice_name:'Capitol Cardiology', payer_name:'Humana', service_date:'2024-12-20', total_charge:2200, total_paid:0, patient_resp:0, status:'denied', primary_icd:'I25.10', cpt_codes:'93306', days_in_ar:72, provider:'Dr. Anita Patel', filing_date:'2024-12-21', denial_code:'CO-50', denial_reason:'Not deemed medically necessary' },
  { id:'7', claim_number:'CLM-2024-00007', patient_name:'James Taylor', practice_name:'Capitol Cardiology', payer_name:'Blue Cross Blue Shield TX', service_date:'2025-02-01', total_charge:500, total_paid:null, patient_resp:null, status:'rejected', primary_icd:'I10', cpt_codes:'99213, 93000', days_in_ar:29, provider:'Dr. Anita Patel', filing_date:'2025-02-02', rejection_reason:'Invalid member ID format' },
  { id:'8', claim_number:'CLM-2024-00008', patient_name:'Charles Harris', practice_name:'Austin Family Medicine', payer_name:'Blue Cross Blue Shield TX', service_date:'2024-10-15', total_charge:1800, total_paid:0, patient_resp:0, status:'appealed', primary_icd:'M47.812', cpt_codes:'22551, 22552', days_in_ar:140, provider:'Dr. Emily Chen', filing_date:'2024-10-16', denial_code:'CO-4', denial_reason:'Modifier mismatch' },
  { id:'9', claim_number:'CLM-2025-00009', patient_name:'Barbara Thomas', practice_name:'Rocky Mountain Primary Care', payer_name:'Anthem', service_date:'2025-02-10', total_charge:180, total_paid:115.20, patient_resp:28.80, status:'paid', primary_icd:'J20.9', cpt_codes:'99213', days_in_ar:0, provider:'Dr. Sarah Kim', filing_date:'2025-02-11' },
  { id:'10', claim_number:'CLM-2025-00010', patient_name:'Richard Jackson', practice_name:'Rocky Mountain Primary Care', payer_name:'UnitedHealthcare', service_date:'2025-02-15', total_charge:320, total_paid:null, patient_resp:null, status:'submitted', primary_icd:'R10.9', cpt_codes:'99214, 76700', days_in_ar:15, provider:'Dr. Sarah Kim', filing_date:'2025-02-16' },
  { id:'11', claim_number:'CLM-2025-00011', patient_name:'Susan White', practice_name:'Peak Performance Sports Med', payer_name:'Cigna', service_date:'2025-02-18', total_charge:600, total_paid:null, patient_resp:null, status:'scrubbing', primary_icd:'S83.511A', cpt_codes:'29881', days_in_ar:12, provider:'Dr. Tom Bradley', filing_date:null },
  { id:'12', claim_number:'CLM-2025-00012', patient_name:'Karen Clark', practice_name:'Austin Family Medicine', payer_name:'Aetna', service_date:'2025-02-20', total_charge:275, total_paid:null, patient_resp:null, status:'ready', primary_icd:'Z00.00', cpt_codes:'99395', days_in_ar:10, provider:'Dr. Emily Chen', filing_date:null },
  { id:'13', claim_number:'CLM-2025-00013', patient_name:'Daniel Lewis', practice_name:'Lone Star Orthopedics', payer_name:'Cigna', service_date:'2025-01-25', total_charge:4500, total_paid:null, patient_resp:null, status:'pending_payer', primary_icd:'M75.110', cpt_codes:'29827', days_in_ar:36, provider:'Dr. Mark Rivera', filing_date:'2025-01-26' },
  { id:'14', claim_number:'CLM-2025-00014', patient_name:'Nancy Robinson', practice_name:'Capitol Cardiology', payer_name:'Humana', service_date:'2025-02-05', total_charge:3800, total_paid:0, patient_resp:0, status:'denied', primary_icd:'I48.91', cpt_codes:'93656', days_in_ar:24, provider:'Dr. Anita Patel', filing_date:'2025-02-06', denial_code:'CO-50', denial_reason:'Medical necessity not established' },
  { id:'15', claim_number:'CLM-2025-00015', patient_name:'Paul Walker', practice_name:'Rocky Mountain Primary Care', payer_name:'Anthem', service_date:'2025-02-22', total_charge:420, total_paid:null, patient_resp:null, status:'draft', primary_icd:'E78.5', cpt_codes:'99214, 80061', days_in_ar:0, provider:'Dr. Sarah Kim', filing_date:null },
];

export const DENIALS = [
  { id:'1', claim_number:'CLM-2024-00005', patient_name:'David Martinez', practice_name:'Lone Star Orthopedics', payer_name:'Medicare', service_date:'2024-11-10', denial_code:'CO-197', denial_category:'authorization', denial_reason:'Precertification/authorization/notification absent. Prior authorization was not obtained for this procedure.', amount_denied:850, status:'appealing', is_appealable:true, appeal_deadline:'2025-04-15', ai_confidence:0.965, ai_classification:{ primary_category:'authorization', root_cause:'missing_prior_auth', recommended_action:'File appeal with operative report, MRI findings, and documentation of urgent medical necessity' } },
  { id:'2', claim_number:'CLM-2024-00006', patient_name:'Linda Anderson', practice_name:'Capitol Cardiology', payer_name:'Humana', service_date:'2024-12-20', denial_code:'CO-50', denial_category:'medical_necessity', denial_reason:'These are non-covered services because this is not deemed a medical necessity by the payer. Clinical documentation does not support the level of service billed.', amount_denied:2200, status:'reviewing', is_appealable:true, appeal_deadline:'2025-05-01', ai_confidence:0.923, ai_classification:{ primary_category:'medical_necessity', root_cause:'insufficient_documentation', recommended_action:'Appeal with detailed clinical notes, diagnostic test results, and peer-reviewed literature supporting medical necessity' } },
  { id:'3', claim_number:'CLM-2024-00008', patient_name:'Charles Harris', practice_name:'Austin Family Medicine', payer_name:'Blue Cross Blue Shield TX', service_date:'2024-10-15', denial_code:'CO-4', denial_category:'coding', denial_reason:'The procedure code is inconsistent with the modifier used or a required modifier is missing. Modifier 22 may be applicable.', amount_denied:1800, status:'correcting', is_appealable:true, appeal_deadline:'2025-02-20', ai_confidence:0.981, ai_classification:{ primary_category:'coding', root_cause:'modifier_mismatch', recommended_action:'Add modifier 22 for increased procedural complexity, include operative note documenting additional work, and resubmit' } },
  { id:'4', claim_number:'CLM-2025-00014', patient_name:'Nancy Robinson', practice_name:'Capitol Cardiology', payer_name:'Humana', service_date:'2025-02-05', denial_code:'CO-50', denial_category:'medical_necessity', denial_reason:'Non-covered service: medical necessity not established per payer clinical policy for cardiac ablation. Documentation does not meet criteria in Humana Clinical Policy CPG-044.', amount_denied:3800, status:'new', is_appealable:true, appeal_deadline:'2025-05-20', ai_confidence:0.894, ai_classification:{ primary_category:'medical_necessity', root_cause:'clinical_policy_not_met', recommended_action:'Gather 12-lead ECG, Holter monitor results, documentation of failed antiarrhythmic therapy, and peer-to-peer review request' } },
];

export const TASKS = [
  { id:'1', task_type:'denial_review', priority:'critical', title:'Review high-value denial: $3,800 cardiac ablation', description:'AI classified as medical necessity denial (89.4% confidence). Nancy Robinson at Capitol Cardiology. Humana requires clinical policy CPG-044 criteria. Recommended: gather supporting cardiac documentation and file appeal before May 20, 2025 deadline.', practice_name:'Capitol Cardiology', status:'open', due_date:'2025-03-10', agent_id:'denial_agent_v1' },
  { id:'2', task_type:'appeal_review', priority:'high', title:'Approve appeal letter for Medicare denial CLM-2024-00005', description:'AI-drafted appeal letter for $850 arthroscopic meniscectomy for David Martinez. Authorization denial (CO-197). Letter references MRI findings showing displaced bucket-handle tear and urgent medical necessity. Ready for human review before submission.', practice_name:'Lone Star Orthopedics', status:'pending_review', due_date:'2025-03-05', agent_id:'appeal_agent_v1' },
  { id:'3', task_type:'auth_followup', priority:'high', title:'Prior auth pending > 5 business days: cardiac catheterization', description:'Prior authorization request for patient James Taylor (BCBS TX) was submitted 5+ business days ago with no response. Standard turnaround is 3-5 days. Recommend calling payer PA department or submitting escalation request.', practice_name:'Capitol Cardiology', status:'open', due_date:'2025-03-04', agent_id:'auth_agent_v1' },
  { id:'4', task_type:'coding_review', priority:'medium', title:'Modifier validation needed: spinal fusion CLM-2024-00008', description:'Claim rejected with CO-4 (modifier mismatch) for Charles Harris spinal fusion procedure. AI analysis suggests adding modifier 22 for increased procedural complexity. Operative note documents significant adhesions requiring additional dissection time. Requires certified coder review before resubmission.', practice_name:'Austin Family Medicine', status:'open', due_date:'2025-03-06', agent_id:'scrub_agent_v1' },
  { id:'5', task_type:'eligibility_failure', priority:'medium', title:'Eligibility check failed for Jennifer Davis (Cigna)', description:'Automated eligibility verification returned error for member ID CIG-33456789. Possible causes: member ID format changed, coverage terminated, or payer system timeout. Manual verification via Cigna provider portal recommended.', practice_name:'Lone Star Orthopedics', status:'open', due_date:'2025-03-04', agent_id:'eligibility_agent_v1' },
  { id:'6', task_type:'claim_aging', priority:'low', title:'Claim CLM-2024-00003 aging at 47 days without update', description:'UnitedHealthcare claim for Michael Brown (diabetes management, $450) was submitted 47 days ago. Last electronic status check showed "pending" with no additional detail. Industry standard is payment within 30 days. Consider phone follow-up or peer review request.', practice_name:'Austin Family Medicine', status:'open', due_date:'2025-03-08', agent_id:'follow_up_agent_v1' },
];

export const AGENTS = [
  { id:'1', agent_type:'eligibility_agent', action_type:'verify_coverage', entity_type:'eligibility_check', status:'completed', processing_time_ms:1250, practice_name:'Austin Family Medicine', created_at:'2025-03-03T10:15:22', details:'Verified BCBS TX coverage for Robert Johnson. Active PPO Gold plan.' },
  { id:'2', agent_type:'eligibility_agent', action_type:'verify_coverage', entity_type:'eligibility_check', status:'completed', processing_time_ms:890, practice_name:'Austin Family Medicine', created_at:'2025-03-03T11:20:45', details:'Verified Aetna coverage for Patricia Williams. Active POS II plan.' },
  { id:'3', agent_type:'claim_scrub_agent', action_type:'validate_claim', entity_type:'claim', status:'completed', processing_time_ms:340, practice_name:'Austin Family Medicine', created_at:'2025-03-03T11:45:10', details:'CLM-2025-00012 passed all validation checks. ICD-10, CPT, demographics verified.' },
  { id:'4', agent_type:'claim_submit_agent', action_type:'submit_to_clearinghouse', entity_type:'claim', status:'completed', processing_time_ms:2100, practice_name:'Austin Family Medicine', created_at:'2025-03-03T12:00:33', details:'CLM-2024-00003 submitted via Availity. 999 acknowledgment received: accepted.' },
  { id:'5', agent_type:'denial_agent', action_type:'classify_denial', entity_type:'denial', status:'completed', processing_time_ms:3200, practice_name:'Lone Star Orthopedics', created_at:'2025-03-03T12:10:15', details:'CLM-2024-00005 denial classified: authorization (96.5% confidence). Root cause: missing prior auth.' },
  { id:'6', agent_type:'appeal_agent', action_type:'draft_appeal_letter', entity_type:'appeal', status:'completed', processing_time_ms:8500, practice_name:'Lone Star Orthopedics', created_at:'2025-03-03T12:15:44', details:'Generated appeal letter for CLM-2024-00005. Citing MRI findings, urgent necessity. Pending human review.' },
  { id:'7', agent_type:'follow_up_agent', action_type:'check_claim_status', entity_type:'claim', status:'completed', processing_time_ms:1800, practice_name:'Austin Family Medicine', created_at:'2025-03-03T12:25:30', details:'CLM-2024-00003 status check: pending at UHC. No change since last inquiry.' },
  { id:'8', agent_type:'eligibility_agent', action_type:'verify_coverage', entity_type:'eligibility_check', status:'failed', processing_time_ms:5200, practice_name:'Lone Star Orthopedics', created_at:'2025-03-03T12:27:18', details:'Cigna eligibility check failed for Jennifer Davis. Member ID not found. Escalated to HITL queue.' },
  { id:'9', agent_type:'denial_agent', action_type:'classify_denial', entity_type:'denial', status:'completed', processing_time_ms:2900, practice_name:'Capitol Cardiology', created_at:'2025-03-03T12:29:55', details:'CLM-2025-00014 denial classified: medical_necessity (89.4% confidence). Humana CPG-044 criteria not met.' },
  { id:'10', agent_type:'posting_agent', action_type:'post_remittance', entity_type:'payment', status:'completed', processing_time_ms:450, practice_name:'Rocky Mountain Primary Care', created_at:'2025-03-03T12:32:10', details:'Posted $115.20 payment from Anthem for CLM-2025-00009. Zero variance.' },
  { id:'11', agent_type:'claim_scrub_agent', action_type:'validate_claim', entity_type:'claim', status:'completed', processing_time_ms:280, practice_name:'Peak Performance Sports Med', created_at:'2025-03-03T12:35:40', details:'CLM-2025-00011 scrub in progress. NCCI edit check passed. Awaiting modifier validation.' },
  { id:'12', agent_type:'eligibility_agent', action_type:'batch_verification', entity_type:'eligibility_check', status:'completed', processing_time_ms:15400, practice_name:'Capitol Cardiology', created_at:'2025-03-03T12:40:05', details:'Batch verification completed for 8 upcoming appointments. 7 verified, 1 needs review.' },
];

export const ELIGIBILITY = [
  { id:'1', patient_name:'Robert Johnson', payer_name:'Blue Cross Blue Shield TX', member_id:'BCB-90012345', plan:'PPO Gold', practice_name:'Austin Family Medicine', status:'verified', coverage_active:true, copay:30, deductible_remaining:550, coinsurance:'20%', processing_time_ms:1250, checked_at:'2025-03-03T10:15:22' },
  { id:'2', patient_name:'Patricia Williams', payer_name:'Aetna', member_id:'AET-78045123', plan:'Choice POS II', practice_name:'Austin Family Medicine', status:'verified', coverage_active:true, copay:25, deductible_remaining:700, coinsurance:'15%', processing_time_ms:890, checked_at:'2025-03-03T11:20:45' },
  { id:'3', patient_name:'Michael Brown', payer_name:'UnitedHealthcare', member_id:'UHC-55123678', plan:'Choice Plus', practice_name:'Austin Family Medicine', status:'verified', coverage_active:true, copay:35, deductible_remaining:2500, coinsurance:'20%', processing_time_ms:2100, checked_at:'2025-03-03T11:30:10' },
  { id:'4', patient_name:'Jennifer Davis', payer_name:'Cigna', member_id:'CIG-33456789', plan:'Open Access Plus', practice_name:'Lone Star Orthopedics', status:'failed', coverage_active:false, copay:null, deductible_remaining:null, coinsurance:null, processing_time_ms:5200, checked_at:'2025-03-03T12:27:18', error:'Member ID not found in payer system' },
  { id:'5', patient_name:'Linda Anderson', payer_name:'Humana', member_id:'HUM-88901234', plan:'Gold Plus HMO', practice_name:'Capitol Cardiology', status:'verified', coverage_active:true, copay:20, deductible_remaining:0, coinsurance:'10%', processing_time_ms:780, checked_at:'2025-03-03T12:30:05' },
  { id:'6', patient_name:'David Martinez', payer_name:'Medicare', member_id:'MBI-1A23B45CD67', plan:'Original Medicare Part B', practice_name:'Lone Star Orthopedics', status:'verified', coverage_active:true, copay:0, deductible_remaining:0, coinsurance:'20%', processing_time_ms:920, checked_at:'2025-03-03T09:45:00' },
  { id:'7', patient_name:'Barbara Thomas', payer_name:'Anthem', member_id:'ANT-12345678', plan:'Blue Access PPO', practice_name:'Rocky Mountain Primary Care', status:'verified', coverage_active:true, copay:30, deductible_remaining:800, coinsurance:'20%', processing_time_ms:1100, checked_at:'2025-03-03T08:30:15' },
];

export const PATIENTS = [
  { id:'1', first_name:'Robert', last_name:'Johnson', mrn:'MRN-10001', dob:'1965-03-15', gender:'M', practice_name:'Austin Family Medicine', payer:'Blue Cross Blue Shield TX', member_id:'BCB-90012345', coverage:'active' },
  { id:'2', first_name:'Patricia', last_name:'Williams', mrn:'MRN-10002', dob:'1978-07-22', gender:'F', practice_name:'Austin Family Medicine', payer:'Aetna', member_id:'AET-78045123', coverage:'active' },
  { id:'3', first_name:'Michael', last_name:'Brown', mrn:'MRN-10003', dob:'1990-11-08', gender:'M', practice_name:'Austin Family Medicine', payer:'UnitedHealthcare', member_id:'UHC-55123678', coverage:'active' },
  { id:'4', first_name:'Jennifer', last_name:'Davis', mrn:'MRN-20001', dob:'1985-01-30', gender:'F', practice_name:'Lone Star Orthopedics', payer:'Cigna', member_id:'CIG-33456789', coverage:'failed' },
  { id:'5', first_name:'David', last_name:'Martinez', mrn:'MRN-20002', dob:'1972-09-14', gender:'M', practice_name:'Lone Star Orthopedics', payer:'Medicare', member_id:'MBI-1A23B45CD67', coverage:'active' },
  { id:'6', first_name:'Linda', last_name:'Anderson', mrn:'MRN-30001', dob:'1958-05-20', gender:'F', practice_name:'Capitol Cardiology', payer:'Humana', member_id:'HUM-88901234', coverage:'active' },
  { id:'7', first_name:'James', last_name:'Taylor', mrn:'MRN-30002', dob:'1970-12-03', gender:'M', practice_name:'Capitol Cardiology', payer:'Blue Cross Blue Shield TX', member_id:'BCB-70045678', coverage:'active' },
  { id:'8', first_name:'Barbara', last_name:'Thomas', mrn:'MRN-40001', dob:'1982-06-18', gender:'F', practice_name:'Rocky Mountain Primary Care', payer:'Anthem', member_id:'ANT-12345678', coverage:'active' },
  { id:'9', first_name:'Richard', last_name:'Jackson', mrn:'MRN-40002', dob:'1995-04-25', gender:'M', practice_name:'Rocky Mountain Primary Care', payer:'UnitedHealthcare', member_id:'UHC-99887766', coverage:'active' },
  { id:'10', first_name:'Susan', last_name:'White', mrn:'MRN-50001', dob:'1988-08-12', gender:'F', practice_name:'Peak Performance Sports Med', payer:'Cigna', member_id:'CIG-11223344', coverage:'active' },
  { id:'11', first_name:'Charles', last_name:'Harris', mrn:'MRN-10004', dob:'1955-02-28', gender:'M', practice_name:'Austin Family Medicine', payer:'Blue Cross Blue Shield TX', member_id:'BCB-90012345', coverage:'active' },
  { id:'12', first_name:'Karen', last_name:'Clark', mrn:'MRN-10005', dob:'1992-10-17', gender:'F', practice_name:'Austin Family Medicine', payer:'Aetna', member_id:'AET-78045123', coverage:'active' },
  { id:'13', first_name:'Daniel', last_name:'Lewis', mrn:'MRN-20003', dob:'1980-07-09', gender:'M', practice_name:'Lone Star Orthopedics', payer:'Cigna', member_id:'CIG-33456789', coverage:'active' },
  { id:'14', first_name:'Nancy', last_name:'Robinson', mrn:'MRN-30003', dob:'1963-11-22', gender:'F', practice_name:'Capitol Cardiology', payer:'Humana', member_id:'HUM-88901234', coverage:'active' },
  { id:'15', first_name:'Paul', last_name:'Walker', mrn:'MRN-40003', dob:'1975-03-05', gender:'M', practice_name:'Rocky Mountain Primary Care', payer:'Anthem', member_id:'ANT-12345678', coverage:'active' },
];

export const PRACTICES = [
  { id:'1', name:'Austin Family Medicine', specialty:'Family Medicine', emr:'Epic', city:'Austin', state:'TX', patients:5, claims:6, total_charges:3125, npi:'1111111111' },
  { id:'2', name:'Lone Star Orthopedics', specialty:'Orthopedics', emr:'athenahealth', city:'Austin', state:'TX', patients:3, claims:3, total_charges:6550, npi:'2222222222' },
  { id:'3', name:'Capitol Cardiology', specialty:'Cardiology', emr:'Cerner', city:'Austin', state:'TX', patients:3, claims:3, total_charges:6500, npi:'3333333333' },
  { id:'4', name:'Rocky Mountain Primary Care', specialty:'Internal Medicine', emr:'Epic', city:'Denver', state:'CO', patients:3, claims:3, total_charges:920, npi:'4444444444' },
  { id:'5', name:'Peak Performance Sports Med', specialty:'Sports Medicine', emr:'athenahealth', city:'Denver', state:'CO', patients:1, claims:1, total_charges:600, npi:'5555555555' },
];

export const PAYMENTS = [
  { id:'1', claim_number:'CLM-2024-00001', patient_name:'Robert Johnson', payer:'Blue Cross Blue Shield TX', amount:160, adjustment:50, patient_resp:40, method:'EFT', eft_number:'EFT-78901', date:'2024-12-20', posted:true, reconciled:true },
  { id:'2', claim_number:'CLM-2024-00002', patient_name:'Patricia Williams', payer:'Aetna', amount:238, adjustment:70, patient_resp:42, method:'EFT', eft_number:'EFT-78902', date:'2024-12-28', posted:true, reconciled:true },
  { id:'3', claim_number:'CLM-2025-00009', patient_name:'Barbara Thomas', payer:'Anthem', amount:115.20, adjustment:36, patient_resp:28.80, method:'EFT', eft_number:'EFT-89001', date:'2025-02-25', posted:true, reconciled:true },
];

export const APPEAL_LETTER = `Dear Medicare Appeals Department,

We are writing on behalf of Lone Star Orthopedics to formally appeal the denial of claim CLM-2024-00005 for our patient, David Martinez (MBI: MBI-1A23B45CD67), for services rendered on November 10, 2024.

PROCEDURE: CPT 29881 — Arthroscopic meniscectomy, medial, right knee
DENIAL CODE: CO-197 — Precertification/authorization/notification absent
AMOUNT IN DISPUTE: $850.00

We respectfully submit that this procedure was performed on an urgent basis following an acute meniscal injury. The patient presented with mechanical locking of the right knee confirmed by physical examination and MRI imaging dated November 5, 2024.

CLINICAL JUSTIFICATION:
The MRI performed on November 5, 2024 demonstrated a displaced bucket-handle tear of the medial meniscus with the displaced fragment lodged in the intercondylar notch, causing true mechanical locking of the knee joint. The patient had failed conservative management including rest, ice, compression, and NSAIDs over the preceding 72 hours with no improvement in mechanical symptoms.

Given the mechanical nature of the obstruction and the patient's inability to achieve full knee extension, surgical intervention was deemed urgently necessary to prevent further cartilage damage and restore joint function. Per Medicare LCD L35041, arthroscopic meniscectomy is considered medically necessary for displaced meniscal tears causing mechanical symptoms that have failed conservative management.

ENCLOSED DOCUMENTATION:
1. MRI report dated November 5, 2024 (Dr. Williams, Austin Radiology)
2. Pre-operative evaluation and history of present illness
3. Operative report dated November 10, 2024 (Dr. Mark Rivera)
4. Post-operative progress notes documenting clinical improvement
5. Letter of medical necessity from Dr. Mark Rivera

We respectfully request reconsideration of this denial and authorization for retrospective payment. Should you require additional information or wish to schedule a peer-to-peer review, please contact our office at (512) 555-2001.

Sincerely,
Meridian Medical Billing
On behalf of Lone Star Orthopedics
Dr. Mark Rivera, MD — Orthopedic Surgery`;
